# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-16 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='passport',
            managers=[
            ],
        ),
    ]
